version: 0.2

phases:
  install:
    commands:
      - echo "installing source NPM dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "testing the lambda function"
      - npm test
      - echo "packing the lambda function"
      - npm run build
  build:
    commands:
      - aws cloudformation package --template-file template.json --s3-bucket topdanmark-dev-02-lambda --output-template-file template-output.yaml
  post_build:
    commands:
      - echo "build completed on `date`"
artifacts:
  files:
    - template-output.yaml
